# Generated by Django 5.1.3 on 2026-09-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_brand_id_alter_cartitem_id_alter_category_id_and_more"),
        ("shop", "0004_order_stock_deducted"),
    ]

    operations = []
